### PR TITLE
Fix generator code for case of responses

### LINKED ISSUE #938: [BUG] issueChannelToken incorrect response
example bug response
{
  access_token: "",
  expires_in: 123456,
  ....
}

should be:
{
  accessToken: "",
  expiresIn: 123456,
  ....
}

### PR DESCRIPTION
**Pull request by mokuzon**
Fix #938

### CODE REVIEW

**Review by Yang-33 — COMMENTED** [review]
Thank you. Can you run `python3 generate.py` in your local to include code generated by script to this change?

**Comment by mokuzon** [comment]
@Yang-33 If I merge this PR, https://github.com/line/line-bot-sdk-nodejs/blob/master/.github/workflows/update-code.yml will run, but you want to see the diff directly on the PR? Is that right?

**Comment by Yang-33** [comment]
> you want to see the diff directly on the PR?

Yes.

**Comment by mokuzon** [comment]
Generated diff: 86e8b5e

**Review by Yang-33 — APPROVED** [review]
@mokuzon thank you for fixing this quickly!!
Please release this as `v9.3.1` 🙏

**Pull request merged**
