### PR TITLE
add X-Line-Retry-Key support

### PR DESCRIPTION
**Pull request by kamnan43**
Add optional parameter to message POST method
(Push / Multicast / Broadcast / Narrowcast)
to support X-Line-Retry-Key

### CODE REVIEW

**Comment by xingoxu** [comment]
#219

**Comment by xingoxu** [comment]
I think maybe `X-LINE-Retry-Key` will not only be supported in those four API in future so I would like to use some as 

`setRetryKey(retryKey: string)`

then when it sends request, it includes the retryKey if it exists.

How do you think?

**Comment by kamnan43** [comment]
Your concern is acceptable.
But If we use `setRetryKey`, It may also need `clearRetryKey` ?.

Or if we automatic clear retryKey after request sent.
When we loop through API for more than 500 users,
it has to call both `setRetryKey` and (for example) `client.multicast` for every loop call

I think optional parameter is do its function properly.
Is it acceptable to add optional parameters to additional support API in the future.

**Comment by xingoxu** [comment]
When you send same message to different users by using multicast, I think you only need to generate and set retry key only once. Loop shouldn't exist.

Could you show me your code about this concept? I want to know how you will use this function.

**Comment by kamnan43** [comment]
In case I want to multicast to more than 500 uids.
For example, If I'd like to send same message to 100,000 uids,
I have to loop 200 times to call multicast API request (limited 500 uids per request)
with same message but difference retryKey.

**Comment by xingoxu** [comment]
Actually what I am considering is, for example, `narrowcast` has already had 5 parameters to pass. That's a bit too long and it's definitely not a good practice.

I think we can make an API like `client.setOptionOnce({ retryKey: string })`. Do you think it's acceptable?

**Comment by kamnan43** [comment]
Excellent, focus on problem and come with great solution!
Deal!

ในวันที่ อ. 19 พ.ค. 2020 เวลา 18:44 xingo xu <notifications@github.com>
เขียนว่า:

**Comment by kamnan43** [comment]
But another idea, what happen if I prepare statement like this.

```
client.setOptionOnce({ retryKey: 'xxxxxx' });
client.narrowcast(...);
```

but some other thread take that option like this

```
client.setOptionOnce({ retryKey: 'xxxxxx' });
client.pushMessage(...) // from another thread take that option!
client.narrowcast(...); // will call without retrykey
```

How about to group narrowcast parameters to one object like `updateUploadAudienceGroup` function

**Comment by xingoxu** [comment]
First, nodejs doesn't exist real multi-threading.
And also I'm going to make the option(retryKey) be taken and reset synchronously.
I'll submit a pull request tomorrow and I think you can take a look at that time.

**Comment by kamnan43** [comment]
Oops, I miss it, sorry.
Thank for your guide.

**Pull request closed without merging**
