### PR TITLE
add api "Get group/room member profiles"

### PR DESCRIPTION
**Pull request by chooco13**
add api "[get-group-room-member-profiles](https://devdocs.line.me/en/#get-group-room-member-profiles)"

before pull request, I want to apply my adding api functions to my bot. 
But, I don't know how.
I'm not goot at node.js ;(

I would be grateful if you could tell me how to test it.

### CODE REVIEW

**Comment by noraesae** [comment]
Thanks! The PR seems good. I will merge this.

About applying this methods, you should have a room ID (or group ID) and a user ID in advance. You can get the IDs from webhook if your bot is in the room or group and the user sends something.

If there's still anything unclear, please feel free to upload an issue.

Thanks!

**Comment by chooco13** [comment]
sorry about my poor English ;(

I asked about "how can i use developing module not using module from npm" 
Because I want to test my code before pull-request

Now it 's merged, it does not matter.
Thanks!

When I can use new module from npm?

**Comment by noraesae** [comment]
Oh, now I get it.

Guessing the project is in the directory `~/Work/line-bot-sdk-nodejs`, You can require it with `require('line-bot-sdk-nodejs')` if `NODE_PATH` is set the parent directory of the project, in this case `~/Work`. Please ensure that TS is built into JS and the results exist in `dist`.

**Comment by noraesae** [comment]
I am not sure when the next release will be, but I guess not so far. Stay tuned :)

**Pull request merged**
