### PR TITLE
Node version up and use async await

### LINKED ISSUE #131: Support Node.js 12
Node.js 12 will be out in a while. I assume the current code just works in Node.js 12, but we should ensure it by adding 12 to CI test environments.

https://github.com/nodejs/Release

### PR DESCRIPTION
**Pull request by utatti**
Resolve #131 and #126.

By the Node.js LTS schedule, Node.js 6 has been deprecated and 12 has been released.

This pull request updates npm and Travis configs for the upgrades.

Also, later parts of this p-r applies async-await to the code base because it's supported natively from Node.js 8.

### CODE REVIEW

**Comment by potato4d** [comment]
I want to refactor the type definition...

**Comment by tkgauri** [comment]
@utatti @kawasako Do we need to update "Requirements" in the README file from `Node.js 6 or higher` to `Node.js 12 or higher` ?

**Comment by utatti** [comment]
@tkgauri I've updated it to `8 or higher` in this p-r.

**Comment by kawasako** [comment]
Thank you for the work. I'm sorry that confirmation is late.

**Pull request merged**
