### PR TITLE
Fix LINEThings Scenario Execution Event Types

### PR DESCRIPTION
**Pull request by xingoxu**
fix https://github.com/line/line-bot-sdk-nodejs/pull/150#issuecomment-508062838

@SombreroElGringo @joseph1125 
Please come and see.

### CODE REVIEW

**Comment by SombreroElGringo** [comment]
On the example of the official [documentation](https://developers.line.biz/en/reference/messaging-api/#scenario-result-event) we can receive an array of `events` and the `destination`.

**Comment by xingoxu** [comment]
@SombreroElGringo 
Yes, I saw that.
But if it is that, the response will come and become
```
{
  destination:'destination',
  events: [{
     destination: 'destination',
     events: [{ ... }]
  }]
}
```
this.

So I guess it's just maybe a mistake by someone wrote the document.
I will ask and confirm it tomorrow.

**Comment by xingoxu** [comment]
@SombreroElGringo I've confirmed with document writer.
The example of LINE Things Scenario Execution Event is webhook response. So this pr is no problem.

And they're going to fix the document and deciding which format should be the example.

**Comment by kawasako** [comment]
I checked it on codebase only.

**Pull request merged**
