### PR TITLE
Fix quote cause prettier error on Windows

### PR DESCRIPTION
**Pull request by micksatana**
Solve #37

### CODE REVIEW

**Comment by utatti** [comment]
Hello, thank you for your contribution.

I'm sorry if you've already done, but can you please sign the contributor license agreement?

- [CONTRIBUTING.md#contributor-license-agreement](https://github.com/line/line-bot-sdk-nodejs/blob/master/CONTRIBUTING.md#contributor-license-agreement)

Thanks in advance.

**Comment by utatti** [comment]
Thanks!

**Comment by micksatana** [comment]
Signed. ( ^^)b

**Comment by utatti** [comment]
Oh, thanks. I actually deleted my comment about ICLA, as it's a minor doc fix rather than source-level modification. But anyway, thanks again for your contribution!

**Pull request merged**
